AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
Documentation:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Lint/RedundantRequireStatement:
  Exclude:
    - lib/shrink/all.rb
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/IfUnlessModifier:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
